### ISSUE TITLE
Offset argument contained a NaN value

### ISSUE THREAD

**Issue by papakay** [mzimmerm/flutter_charts#18]
Hi, I want to really commend the great work done so far with this library.

I experience the error above when i have data rows as below

```dart
_chartData.dataRows = [
      [0.0, 0.0, 0.0, 0.0, 0.0],
      [0.0, 0.0, 0.0, 0.0, 0.0],
      [0.0, 0.0, 0.0, 0.0, 0.0],
      [0.0, 0.0, 0.0, 0.0, 0.0],
    ];
```

Part of the error message:

```dart
flutter: ══╡ EXCEPTION CAUGHT BY RENDERING LIBRARY ╞═════════════════════════════════════════════════════════
flutter: The following assertion was thrown during paint():
flutter: Offset argument contained a NaN value.
flutter: 'dart:ui/painting.dart': Failed assertion: line 38: '<optimized out>'
flutter:
flutter: Either the assertion indicates an error in the framework itself, or we should provide substantially
flutter: more information in this error message to help you determine and fix the underlying cause.
flutter: In either case, please report this assertion by filing a bug on GitHub:
flutter:   https://github.com/flutter/flutter/issues/new?template=BUG.md
flutter:
flutter: When the exception was thrown, this was the stack:
flutter: #2      _offsetIsValid (dart:ui/painting.dart:38:10)
flutter: #3      Canvas.drawLine (dart:ui/painting.dart:3146:12)
flutter: #4      LineContainer.paint (package:flutter_charts/src/chart/line_container.dart:20:12)
flutter: #5      GridLinesContainer.paint.<anonymous closure> (package:flutter_charts/src/chart/container.dart:1094:62)
flutter: #6      List.forEach (dart:core/runtime/libgrowable_array.dart:277:8)
flutter: #7      GridLinesContainer.paint (package:flutter_charts/src/chart/container.dart:1094:21)
flutter: #8      DataContainer.paint (package:flutter_charts/src/chart/container.dart:1028:31)
flutter: #9      ChartPainter.drawGrid (package:flutter_charts/src/chart/painter.dart:76:29)
flutter: #10     ChartPainter.paint (package:flutter_charts/src/chart/painter.dart:55:5)
flutter: #11     RenderCustomPaint._paintWithPainter (package:flutter/src/rendering/custom_paint.dart:521:13)
flutter: #12     RenderCustomPaint.paint (package:flutter/src/rendering/custom_paint.dart:559:7)
flutter: #13     RenderObject._paintWithContext
```

**Comment by ruan65** [comment]
mee too

**Comment by vikramacn5** [comment]
hey, Papakay I had the same issue when using the flutter sparkline package the problem was, the package tried to calculate the maximum and minimum from the list data you are providing with which it allocates the height and plots the graph. But when I fill the list data with full of zeros or with full of same value it can't find the maximum or minimum value so it shows the error. So what I did was I copied all the code from that package and pasted it in a new dart file and changed the code like, if all the values are zeros the minimum value is zero and the maximum value is 1 and when if all the values are same but not zeros assign the minimum as zero and maximum as the value that came after that I imported that file to the dart file where I needed the graph, worked as expected.


_**This is their code**_
class _SparklinePainter extends CustomPainter {
  _SparklinePainter(
    this.dataPoints, {
    @required this.lineWidth,
    @required this.lineColor,
    this.lineGradient,
    @required this.sharpCorners,
    @required this.fillMode,
    @required this.fillColor,
    this.fillGradient,
    @required this.pointsMode,
    @required this.pointSize,
    @required this.pointColor,
  })  : _max = dataPoints.reduce(math.max),
        _min = dataPoints.reduce(math.min);

  final List<double> dataPoints;

  final double lineWidth;
  final Color lineColor;
  final Gradient lineGradient;

  final bool sharpCorners;

  final FillMode fillMode;
  final Color fillColor;
  final Gradient fillGradient;

  final PointsMode pointsMode;
  final double pointSize;
  final Color pointColor;

  final double _max;
  final double _min;

  @override
  void paint(Canvas canvas, Size size) {
    final double width = size.width - lineWidth;
    final double height = size.height - lineWidth;
    final double widthNormalizer = width / (dataPoints.length - 1);
    final double heightNormalizer = height / (_max - _min);

    final Path path = new Path();
    final List<Offset> points = <Offset>[];

    Offset startPoint;

    for (int i = 0; i < dataPoints.length; i++) {
      double x = i * widthNormalizer + lineWidth / 2;
      double y =
          height - (dataPoints[i] - _min) * heightNormalizer + lineWidth / 2;

      if (pointsMode == PointsMode.all) {
        points.add(new Offset(x, y));
      }

      if (pointsMode == PointsMode.last && i == dataPoints.length - 1) {
        points.add(new Offset(x, y));
      }

      if (i == 0) {
        startPoint = new Offset(x, y);
        path.moveTo(x, y);
      } else {
        path.lineTo(x, y);
      }
    }




_**This is what I changed from their code**_
class _SparkLinePainter extends CustomPainter {
  _SparkLinePainter(
    this.dataPoints, {
    @required this.lineWidth,
    @required this.lineColor,
    this.lineGradient,
    @required this.sharpCorners,
    @required this.fillMode,
    @required this.fillColor,
    this.fillGradient,
    @required this.pointsMode,
    @required this.pointSize,
    @required this.pointColor,
  });
//      : _max = dataPoints.reduce(math.min),
//        _min = dataPoints.reduce(math.max);

  final List<double> dataPoints;

  final double lineWidth;
  final Color lineColor;
  final Gradient lineGradient;

  final bool sharpCorners;

  final FillMode fillMode;
  final Color fillColor;
  final Gradient fillGradient;

  final PointsMode pointsMode;
  final double pointSize;
  final Color pointColor;

  //final double _max;
  //final double _min;

  @override
  void paint(Canvas canvas, Size size) {
    double _minTest() {
      double a = 0;
      for (var i = 0; i < dataPoints.length - 1; i++) {
        if (dataPoints[i] == dataPoints[i + 1]) {
          a = a + dataPoints[i];
        } else {
          return dataPoints.reduce(math.min);
          //break;
        }
      }
      a = a + dataPoints[dataPoints.length - 1];
      if (a == 0) {
        return 0;
      } else {
        return 0;
      }
    }

    //0 1 2 3 4 5 6 7
    //[0,0,0,0,0,0,0,0,0]
    double _maxTest() {
      double b = 0;
      for (var i = 0; i < dataPoints.length - 1; i++) {
        if (dataPoints[i] == dataPoints[i + 1]) {
          b = b + dataPoints[i];
        } else {
          return dataPoints.reduce(math.max);
          //break;
        }
      }
      b = b + dataPoints[dataPoints.length - 1];
      if (b != 0) {
        return dataPoints[0];
      } else {
        return 1;
      }
    }

    print(_minTest());
    print(_maxTest());
    final double width = size.width - lineWidth;
    final double height = size.height - lineWidth;
    final double widthNormalizer = width / (dataPoints.length - 1);
    final double heightNormalizer = height / (_maxTest() - _minTest());

    final Path path = new Path();
    final List<Offset> points = <Offset>[];

    Offset startPoint;

    for (int i = 0; i < dataPoints.length; i++) {
      double x = i * widthNormalizer + lineWidth / 2;
      double y = height -
          (dataPoints[i] - _minTest()) * heightNormalizer +
          lineWidth / 2;

      if (pointsMode == PointsMode.all) {
        points.add(new Offset(x, y));
      }

      if (pointsMode == PointsMode.last && i == dataPoints.length - 1) {
        points.add(new Offset(x, y));
      }

      if (i == 0) {
        startPoint = new Offset(x, y);
        path.moveTo(x, y);
      } else {
        path.lineTo(x, y);
      }
    }

I wrote a function for calculating the maximum and minimum try and see I hope it will work for you too.

**Comment by mzimmerm** [comment]
@papakay : Thanks very much for reporting this, and my appologies for the delay. If still relevant: This "all zeros issue" is now fixed in the latest version 0.3.1. Please take a look at

https://pub.dev/packages/flutter_charts/changelog

An example that failed before the change and is now fixed can be seen in 

https://github.com/mzimmerm/flutter_charts/blob/master/example1/lib/main.dart

around 

```dart
      case ExamplesEnum.ex900ErrorFixUserDataAllZero:
        /// Currently, setting [ChartDate.dataRows] requires to also set all of 
        /// [chartData.xLabels], [chartData.dataRowsLegends], [chartData.dataRowsColors]
        // Fix was: Add default legend to ChartData constructor AND fix scaling util_dart.dart scaleValue.
        chartData = ChartData();
        chartData.dataRows = [
          [0.0, 0.0, 0.0],
        ];
        // Note: When ChartData is defined, 
        //       ALL OF  chartData.xLabels,  chartData.dataRowsLegends, chartData.dataRowsColors
        //       must be set by client
        chartData.xLabels = ['Wolf', 'Deer', 'Mouse'];
        chartData.dataRowsLegends = [
          'Row 1',
        ];
        chartData.dataRowsColors = [
          Colors.blue,
        ];
```

**Comment by mzimmerm** [comment]
@papakay Thanks again for reporting this issue. As this is now working (as of 0.3.1) I will go ahead and close this item.

**Comment by papakay** [comment]
Thanks a lot @mzimmerm for the great work!
