### ISSUE TITLE
How to hide legend

### ISSUE THREAD

**Issue by moda20** [mzimmerm/flutter_charts#21]
is there a solution for not showing the legend ( I don't want to see the squares with different colors).

**Comment by fldvlpr** [comment]
@moda20 @mzimmerm Can you please let us know that is it possible to hide legends anyway?

**Comment by mzimmerm** [comment]
Currently there is no way to hide the legend, the x labels or the y labels. But I need that myself, so I will release a version that allows to hide the legend (that works already in my branch), and also the x labels and y labels. That requires a bit more than a few lines, but I feel I should have that in a few days. This work is on a branch that may require a version-jump due to some API changes, although I think it should not be a problem for most clients to just plug in the version-jump. Anyway, I will announce that here when ready.

**Comment by mzimmerm** [comment]
@moda20 : If this is still relevant, I released a new version 0.3.0, which shows how to hide one or more of: the legend, x labels, y labels, grid lines. Please refer to the README file https://github.com/mzimmerm/flutter_charts#new-in-the-current-release and the example1/lib/main.dart for an example.
